server:
  port: 8092
spring:
  profiles:
    include: common
  datasource:
    url: jdbc:mysql://localhost:3306/srivenb8_vbrs
    username: root
    password: 1309
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  aop:
    proxy-target-class: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: pbtjava@gmail.com
    password: jcnsrxqjifkrvqxl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    allow-circular-references: true
    # Multipart configuration
    servlet:
      multipart:
        enabled: true
        max-file-size: 2GB
        max-request-size: 2GB
  thymeleaf:
    cache: false
file:
  upload:
    path: 'D:\PaySlip_WS\Documents\'
